#version 450
/* Copyright (c) 2025, Contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Continuous SDF ring with arc-sampled rotation blur. Radius and half-width
 * are generated by sdf_lut.comp and stored in a compact angular SSBO.
 */

precision highp float;

layout(set = 0, binding = 0, std140) uniform UBO
{
	vec4 viewport;   // center.xy, resolution.xy
	vec4 blur;       // sweep radians, max samples, unused, unused
	vec4 shape;      // base radius, half-width, displacement, location frequency
	vec4 noise;      // time frequency, time, size rate, reform noise
} ubo;

layout(set = 0, binding = 1, std430) readonly buffer RingLUT
{
	vec2 values[];
} ringLut;

layout(location = 0) in vec2 vUV;
layout(location = 0) out vec4 outColor;

const float TWO_PI = 6.28318530718;
const uint LUT_MASK = 255u;

vec2 lut(float angle)
{
	float x = fract(angle / TWO_PI) * 256.0 - 0.5;
	float base = floor(x);
	float t = fract(x);
	uint i0 = uint(int(base)) & LUT_MASK;
	uint i1 = (i0 + 1u) & LUT_MASK;
	return mix(ringLut.values[i0], ringLut.values[i1], t);
}

vec3 ringColor(float angle)
{
	float h = angle / TWO_PI;
	return 0.5 + 0.5 * cos(TWO_PI * (h + vec3(0.0, 0.33, 0.67)));
}

float coverage(float dist, float radius, float halfWidth)
{
	float sd = abs(dist - radius) - halfWidth;
	float aa = max(fwidth(sd), 0.75);
	return 1.0 - smoothstep(0.0, aa, sd);
}

void main()
{
	vec2 center = ubo.viewport.xy;
	vec2 resolution = ubo.viewport.zw;
	vec2 d = (vUV - center) * resolution;
	float dist = length(d);
	float angle = atan(d.y, d.x);
	float resY = resolution.y;

	const float PERLIN_BOUND = 1.75;
	float maxHalfWidth = ubo.shape.y *
	    (1.0 + abs(ubo.noise.z * 5.0 * ubo.noise.w) * PERLIN_BOUND);
	float radialExtent = (abs(ubo.shape.z) * PERLIN_BOUND + maxHalfWidth) * resY + 2.0;
	if (abs(dist - ubo.shape.x * resY) > radialExtent)
	{
		outColor = vec4(0.0);
		return;
	}

	float blurAngle = ubo.blur.x;
	if (abs(blurAngle) < 1e-6)
	{
		vec2 rt = lut(angle);
		float cov = coverage(dist, rt.x * resY, rt.y * resY);
		outColor = vec4(ringColor(angle) * cov, cov);
		return;
	}

	vec2 centerRt = lut(angle);
	float centerHalfWidth = max(centerRt.y * resY, 0.75);
	float arcLength = dist * abs(blurAngle);
	uint maxSamples = max(uint(ubo.blur.y), 1u);
	uint sampleCount = uint(clamp(ceil(arcLength / centerHalfWidth), 1.0, float(maxSamples)));

	vec4 acc = vec4(0.0);
	float invCount = 1.0 / float(sampleCount);
	for (uint i = 0u; i < sampleCount; ++i)
	{
		float t = (float(i) + 0.5) * invCount;
		float sampleAngle = angle + t * blurAngle;
		vec2 rt = lut(sampleAngle);
		float cov = coverage(dist, rt.x * resY, rt.y * resY);
		acc += vec4(ringColor(sampleAngle) * cov, cov);
	}

	// Premultiplied color; the pipeline uses ONE, ONE_MINUS_SRC_ALPHA.
	outColor = acc * invCount;
}
