#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0) readonly buffer SpatialHashIn {
    uint spatial_hash[];
};

layout(std430, binding = 1) buffer CellCountOut {
    uint cell_count[];
};

layout(push_constant) uniform CellCountPC {
    uint  particle_count;
    uint  grid_points;
    float pad1;
    float pad2;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= pc.particle_count) return;
    
    uint hash = spatial_hash[idx];
    
    atomicAdd(cell_count[hash], 1);
}